### ISSUE TITLE
Why removed not only noise, but also parts of the image?

### ISSUE THREAD

**Issue by My12123** [lllyasviel/AdverseCleaner#2]
The image has become less detailed.
original
![421_o](https://user-images.githubusercontent.com/49092250/227262029-2002e3f6-07a9-4ade-9aff-463599d312ed.png)
after processing
![image](https://user-images.githubusercontent.com/49092250/227262173-34a8b99d-9414-43df-895a-454b74206103.png)
![227263185-daf88fe5-94f5-4fbe-92e9-72e9dc7656a4](https://user-images.githubusercontent.com/49092250/227266540-7957e1aa-e70b-46d0-9efc-f0d87ba3c32d.png)

**Comment by alkeryn** [comment]
well it is a filter that removes noise, so it may see small details as noise.

**Comment by My12123** [comment]
Can this be remedied?

**Comment by vladlearns** [comment]
@My12123 This explanation might help: https://github.com/lllyasviel/AdverseCleaner/pull/3
